//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameDateParsing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NameDateParsing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about,abt,a ,circa,cca,cir,ca,est,estimated,c,approximately,approx,approx..
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.d..
        /// </summary>
        internal static string AD {
            get {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after,post,aft,after:,aft..
        /// </summary>
        internal static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.c..
        /// </summary>
        internal static string BC {
            get {
                return ResourceManager.GetString("BC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.c.e..
        /// </summary>
        internal static string BCE {
            get {
                return ResourceManager.GetString("BCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before,ante,bef,by,before:,bef.,B ,b ,B. ,b. .
        /// </summary>
        internal static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between,bet,bet.,estbetween,estbetween:,between:,btw,btw..
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calculated,cal.
        /// </summary>
        internal static string Calculated {
            get {
                return ResourceManager.GetString("Calculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.e..
        /// </summary>
        internal static string CE {
            get {
                return ResourceManager.GetString("CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About:.
        /// </summary>
        internal static string DateAbout {
            get {
                return ResourceManager.GetString("DateAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD.
        /// </summary>
        internal static string DateAD {
            get {
                return ResourceManager.GetString("DateAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC.
        /// </summary>
        internal static string DateBC {
            get {
                return ResourceManager.GetString("DateBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCE.
        /// </summary>
        internal static string DateBCE {
            get {
                return ResourceManager.GetString("DateBCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between:.
        /// </summary>
        internal static string DateBetween {
            get {
                return ResourceManager.GetString("DateBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE.
        /// </summary>
        internal static string DateCE {
            get {
                return ResourceManager.GetString("DateCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIC.
        /// </summary>
        internal static string DateKeywordBIC {
            get {
                return ResourceManager.GetString("DateKeywordBIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string DateKeywordCancelled {
            get {
                return ResourceManager.GetString("DateKeywordCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        internal static string DateKeywordChild {
            get {
                return ResourceManager.GetString("DateKeywordChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared.
        /// </summary>
        internal static string DateKeywordCleared {
            get {
                return ResourceManager.GetString("DateKeywordCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string DateKeywordCompleted {
            get {
                return ResourceManager.GetString("DateKeywordCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead.
        /// </summary>
        internal static string DateKeywordDead {
            get {
                return ResourceManager.GetString("DateKeywordDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deceased.
        /// </summary>
        internal static string DateKeywordDeceased {
            get {
                return ResourceManager.GetString("DateKeywordDeceased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS.
        /// </summary>
        internal static string DateKeywordDNS {
            get {
                return ResourceManager.GetString("DateKeywordDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS/CAN.
        /// </summary>
        internal static string DateKeywordDNSCAN {
            get {
                return ResourceManager.GetString("DateKeywordDNSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DateKeywordDone {
            get {
                return ResourceManager.GetString("DateKeywordDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant.
        /// </summary>
        internal static string DateKeywordInfant {
            get {
                return ResourceManager.GetString("DateKeywordInfant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Married.
        /// </summary>
        internal static string DateKeywordNeverMarried {
            get {
                return ResourceManager.GetString("DateKeywordNeverMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Married.
        /// </summary>
        internal static string DateKeywordNotMarried {
            get {
                return ResourceManager.GetString("DateKeywordNotMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-1970.
        /// </summary>
        internal static string DateKeywordPre1970 {
            get {
                return ResourceManager.GetString("DateKeywordPre1970", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string DateKeywordPrivate {
            get {
                return ResourceManager.GetString("DateKeywordPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stillborn.
        /// </summary>
        internal static string DateKeywordStillborn {
            get {
                return ResourceManager.GetString("DateKeywordStillborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        internal static string DateKeywordSubmitted {
            get {
                return ResourceManager.GetString("DateKeywordSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncleared.
        /// </summary>
        internal static string DateKeywordUncleared {
            get {
                return ResourceManager.GetString("DateKeywordUncleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string DateKeywordUnknown {
            get {
                return ResourceManager.GetString("DateKeywordUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Young.
        /// </summary>
        internal static string DateKeywordYoung {
            get {
                return ResourceManager.GetString("DateKeywordYoung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abt..
        /// </summary>
        internal static string DateModifierAbout {
            get {
                return ResourceManager.GetString("DateModifierAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aft..
        /// </summary>
        internal static string DateModifierAfter {
            get {
                return ResourceManager.GetString("DateModifierAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bef..
        /// </summary>
        internal static string DateModifierBefore {
            get {
                return ResourceManager.GetString("DateModifierBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cal..
        /// </summary>
        internal static string DateModifierCalculated {
            get {
                return ResourceManager.GetString("DateModifierCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or:.
        /// </summary>
        internal static string DateOr {
            get {
                return ResourceManager.GetString("DateOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range:.
        /// </summary>
        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet. {{0:{0}}}–{{1:{0}}}.
        /// </summary>
        internal static string DateRangeFormat {
            get {
                return ResourceManager.GetString("DateRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No name&gt;.
        /// </summary>
        internal static string PersonNameUnknown {
            get {
                return ResourceManager.GetString("PersonNameUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quarter,qtr,qtr..
        /// </summary>
        internal static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range,from,to,and,range:.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string WeekDaysFriday {
            get {
                return ResourceManager.GetString("WeekDaysFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string WeekDaysMonday {
            get {
                return ResourceManager.GetString("WeekDaysMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string WeekDaysSaturday {
            get {
                return ResourceManager.GetString("WeekDaysSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string WeekDaysSunday {
            get {
                return ResourceManager.GetString("WeekDaysSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string WeekDaysThursday {
            get {
                return ResourceManager.GetString("WeekDaysThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string WeekDaysTuesday {
            get {
                return ResourceManager.GetString("WeekDaysTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string WeekDaysWednesday {
            get {
                return ResourceManager.GetString("WeekDaysWednesday", resourceCulture);
            }
        }
    }
}
